# Generated by Django 5.0.4 on 2024-04-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='likesCount',
            field=models.IntegerField(default=0),
        ),
    ]
